### ISSUE TITLE
Nodes and models cannot be used

### ISSUE THREAD

**Issue by YMM0123456789** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#1]
![微信图片_20240817142356](https://github.com/user-attachments/assets/ba5acde2-6b63-4bd9-adcb-fbea702befe7)
![微信图片_20240817142426](https://github.com/user-attachments/assets/43a93496-d12f-476a-a5d6-5e256cc993fc)
hello，The model file has been downloaded, but the startup interface prompts that the model cannot be used due to the red node on the work interface. Can the problem be solved?

**Comment by weilin9999** [comment]
thank for,but today i fix this bug,please update the plugin to the latest version，but i'm not update in release, you must update from git

**Comment by YMM0123456789** [comment]
Thank you, I'll give it a try.

**Comment by YMM0123456789** [comment]
![微信截图_20240817145635](https://github.com/user-attachments/assets/7b82a049-4fd9-478d-819d-4ca1c539f8e6)
![微信截图_20240817165625](https://github.com/user-attachments/assets/a14c5357-c37b-41d0-beb8-771c5ba725f9)
![1](https://github.com/user-attachments/assets/867d1b51-d4c7-413f-9878-907662843ff6)
![2](https://github.com/user-attachments/assets/7a85c81d-6eb8-4da3-b2a1-daf32150726d)
hello，There are no errors in the interface and work interface,There is a problem with the UI display, and the prompt words are not working.
The same prompt words, the first image uses nodes, and the last image does not use nodes,

**Comment by weilin9999** [comment]
your plugin did not start correctly, maybe there is a problem with your ComfyUI environment. can you take a screenshot showing all the content displayed on the console in developer mode of the browser? It can help me discover errors.

**Comment by weilin9999** [comment]
and make sure that the last update time for your plugin is today 2024/8/17 midafternoon

**Comment by YMM0123456789** [comment]
![6](https://github.com/user-attachments/assets/fb44e512-decb-499a-817e-b0bef28b3c69)
![5](https://github.com/user-attachments/assets/d78d3fed-bd01-4a62-86d3-14fd96d8f4c9)
我之前使用时没问题的，现在我退到最早的版本也会报错，提示节点缺失。

**Comment by YMM0123456789** [comment]
I had no problem using it before, but now even when I revert back to the earliest version, I get an error message indicating that the node is missing.
![6](https://github.com/user-attachments/assets/7ec36e7d-dd50-41fe-9f0e-c5b8bc8e14a0)
![5](https://github.com/user-attachments/assets/9901dc82-b1d4-456f-8b50-f1b59ed76452)

**Comment by weilin9999** [comment]
have you ever tried removing nodes and then creating them again

**Comment by weilin9999** [comment]
there are no errors related to this plugin in your console, so I cannot confirm what the problem is

**Comment by YMM0123456789** [comment]
I tried deleting nodes and then recreating them, but it didn't work

**Comment by weilin9999** [comment]
what if it's reinstalling the plugin?

**Comment by YMM0123456789** [comment]
tried

**Comment by weilin9999** [comment]
I am currently unable to confirm what the issue is. Please try to resolve it as much as possible. You can return the old version for use and try again when I update the next version to see if it works. Alternatively, you can add me on QQ Number: 335663085

**Comment by YMM0123456789** [comment]
Thank you very much. The previous version cannot be used either, it simply shows that the node is missing. Cry, no more fuss, looking forward to your update

**Comment by weilin9999** [comment]
In theory, if you are able to open this interface, it means it is already usable. However, I don't know what the problem is, but your UI has not been properly embedded. Perhaps some files are missing or key information is missing, or there may be plugin conflicts. But it would be best if I could take a closer look at your computer's environment before making further judgments

**Comment by weilin9999** [comment]
if you open my node and look at the developer mode console of the browser, will there be any other errors?

**Comment by YMM0123456789** [comment]
Hello, I haven't been using Comfy recently, nor have I been browsing the community for information. You can take a look at the pictures below.

WeiLin-ComfyUI-prompt-all-in-one 找不到llama_cpp模块，以默认不加载本地大模型，可忽略该提示。
![微信截图_20240826205300](https://github.com/user-attachments/assets/add6442c-f548-4fb3-a3ad-5b0e4ce05a43)
![1](https://github.com/user-attachments/assets/c5cf8e1b-c239-4c64-b59b-feb04b0d885c)
![2](https://github.com/user-attachments/assets/5f26a1d2-0229-428e-9bbc-f5c70dbd72c7)
![3](https://github.com/user-attachments/assets/c2156ca3-03d9-4fed-b406-2b0df9d3fe2b)
![4](https://github.com/user-attachments/assets/865e36ee-0f19-4e1a-a462-fff5b7f0281d)
![5](https://github.com/user-attachments/assets/851001cc-fc2c-47f8-9a1c-a51f061b7d8a)
![6](https://github.com/user-attachments/assets/5b7f0223-acd5-495c-b17a-63c7e307f55e)

**Comment by weilin9999** [comment]
Have you opened a proxy tool? Your problem is that the page access timed out. I don't know if it was caused by you using a proxy tool or modifying certain configurations.

**Comment by weilin9999** [comment]
Or you can upgrade the version of Comfyui and try it out

**Comment by YMM0123456789** [comment]
It is already the latest version of Comfy
I'll try closing the proxy,
There is also an issue where 'WeiLin-CompfyUI-pompt-all-in-one cannot find the llama_cpp module, so the local large model is not loaded by default. This prompt can be ignored'. I have downloaded the model and placed it in the location shown in the picture, but it still prompts that the module cannot be found.

**Comment by YMM0123456789** [comment]
Closing the proxy does not work.

**Comment by weilin9999** [comment]
那个llama的提示不用管，你关闭代理之后关闭启动器然后再开启动器，你这个问题有可能是你系统环境的问题，因为你打开我插件的时候访问不到我那个内置的网页而且提示是超时，所以有可能是代理、系统或者是其它插件冲突了。

**Comment by YMM0123456789** [comment]
谢谢，我重装试试吧。

**Comment by YMM0123456789** [comment]
![1](https://github.com/user-attachments/assets/f26af042-0db7-4110-a5b0-7f837f1954b8)
![2](https://github.com/user-attachments/assets/9ac73131-4f0c-4734-a674-82bb1200cafc)

可以使用了，但是有个问题，一旦链接webui的模型，就无法使用，和之前的情况一样，难道是webui那边模型太多了？

**Comment by weilin9999** [comment]
我这个插件只写了跟comfyui适配的文件目录，不支持你这种方式
