### ISSUE TITLE
请添加一个黑暗模式，由于comfyui是黑底的，你这白色界面有点刺眼

### ISSUE THREAD

**Issue by KXVNO** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#13]

**Comment by weilin9999** [comment]
你好，插件有暗黑模式，在插件设置里面。
![QQ截图20241112204308](https://github.com/user-attachments/assets/fc9076cd-c878-43f3-a5d4-83728f0777c9)

**Comment by KXVNO** [comment]
好的，感谢回复

**Comment by weilin9999** [comment]
感谢你的支持
