### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by boeto** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#2]
运行环境为ubuntu，这个ctypes模块应该是windows下才有的。可以先判断平台是否linux，设置默认为中文
The runtime environment is Ubuntu; the ctypes module is typically available on Windows. You can first check if the platform is Linux and set the default language to Chinese.

https://stackoverflow.com/questions/63533869/module-ctypes-has-no-attribute-windll

**Comment by weilin9999** [comment]
好的，目前还没对Linux环境下测试，下一次版本中会修改，目前插件还在重做。

**Comment by weilin9999** [comment]
新版本已修复
