### ISSUE TITLE
尊敬的开发者您好：如何删除默认提示词 

### ISSUE THREAD

**Issue by vtsst3** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#27]
我想询问如何删除预设的提示词。我在设置选项中没有找到相关选项。请问这些预设提示词的信息存储在哪个目录下？
如果能告知具体的文件位置，将不胜感激。谢谢

**Comment by Su3222** [comment]
\custom_nodes\WeiLin-ComfyUI-prompt-all-in-one\group_tags\
![QQ截图20241219182316](https://github.com/user-attachments/assets/20442d24-49c6-455c-88bc-90bf1c420bf8)

**Comment by vtsst3** [comment]
谢谢你用图解给我讲解，让我一下就明白了！
