### ISSUE TITLE
功能缺陷：lora的信息备注太长ui会被拉长看不到右边内容

### ISSUE THREAD

**Issue by nicegamer12** [weilin9999/WeiLin-ComfyUI-prompt-all-in-one#3]
感谢大佬移植！发现有些小bug，首先lora备注只要用回车键换行就会保存，并且一行里字太长ui就会拉长到框外，右边的字和编辑也看不到了，然后无法再编辑
![IMG_20240908_123104](https://github.com/user-attachments/assets/d631daf1-21eb-4970-9a91-e3e04ff97e83)
，

**Comment by weilin9999** [comment]
很高兴你能使用本插件，这个bug后续版本会解决，目前本人还没有空处理这个事情，后续有空了我会异议处理，再次感谢你的支持

**Comment by nicegamer12** [comment]
> 很高兴你能使用本插件，这个bug后续版本会解决，目前本人还没有空处理这个事情，后续有空了我会异议处理，再次感谢你的支持

大佬谦虚了～不急有空再修，还发现另外一个bug，翻译设置里的tagcomplete无法使用，右上角弹出红字，csv文件是没问题的，在webui的时候可以用

**Comment by nicegamer12** [comment]
> 很高兴你能使用本插件，这个bug后续版本会解决，目前本人还没有空处理这个事情，后续有空了我会异议处理，再次感谢你的支持

![Uploading IMG_20240908_233920.jpg…]()

**Comment by nicegamer12** [comment]
> 很高兴你能使用本插件，这个bug后续版本会解决，目前本人还没有空处理这个事情，后续有空了我会异议处理，再次感谢你的支持

![IMG_20240908_233920](https://github.com/user-attachments/assets/e88531fb-6f46-4bbf-b6b2-ede2a941e2ff)

**Comment by weilin9999** [comment]
新版本已修复

**Comment by nicegamer12** [comment]
> 新版本已修复

感谢大佬修复，国庆快乐！不过那个robot dog依旧红框翻译不了，csv文件已经选中了，试了其他csv都不行，不知道是否还要其他操作，另外我添加的很多预设词都被覆盖消失了🤣，没备份

**Comment by weilin9999** [comment]
额，这个情况我是没想到的，我测试的时候还是没问题的，csv文件我测试的时候还是可用用的，你可用把你的csv发给我我试试看

**Comment by nicegamer12** [comment]
> robot dog的翻译问题，我修复了更新的时候忘记替换了，我等等更新一下版本

[danbooru-0-zh.csv](https://github.com/user-attachments/files/17202929/danbooru-0-zh.csv)
[zh_cn_tr.csv](https://github.com/user-attachments/files/17202933/zh_cn_tr.csv)
其实提示词收藏列表也消失了，希望新版本不要覆盖到这些文件

**Comment by weilin9999** [comment]
应该是没有什么问题了，你可以更新试试看

**Comment by weilin9999** [comment]
因为之前仓库清空过重新上传了一次，导致有些排除的文件被上传了

**Comment by weilin9999** [comment]
你还是先备份再更新吧，因为这个github的pull是同步的，备份之后再更新就好了，后续更新就不会再出现这个情况了

**Comment by nicegamer12** [comment]
> robot dog的翻译问题，我修复了更新的时候忘记替换了，我等等更新一下版本



> 应该是没有什么问题了，你可以更新试试看



> 应该是没有什么问题了，你可以更新试试看



> 你先别更新，我刚刚测试了一下，还是有问题，会删除文件，等我改好了再提醒你



> 你先别更新，我刚刚测试了一下，还是有问题，会删除文件，等我改好了再提醒你

robot dog可以翻译了，不过每次更新那个管理自定义词汇就刷新回英文，要重新导入，大佬尽量新版本更新的时候不要覆盖到用户设置😂

**Comment by weilin9999** [comment]
下次不会再替换了，因为我之前清空仓库的时候忘记排除不需要上传的文件了，实在不好意思

**Comment by nicegamer12** [comment]
> 下次不会再替换了，因为我之前清空仓库的时候忘记排除不需要上传的文件了，实在不好意

> 下次不会再替换了，因为我之前清空仓库的时候忘记排除不需要上传的文件了，实在不好意思

顺便向大佬提个功能请求～不知道没有办法做一个像提示词那样可以移动排序的预设词组功能，这样一些常用或者新添加的词组就不用靠太后，虽说原版插件也没有这种功能

**Comment by weilin9999** [comment]
下次更新的时候尽量更新到
